Make the GKI kernel clone-depth="1"
We have to set clone-depth="1" to fix this fetch issue:

  error.GitError: Cannot fetch kernel/common update-ref: fatal: b62a5f6d62b49d1c6a9dd2fc31ede0b08428b7e1^0: not a valid SHA1

Once we move to a valid branch android-mainline or android13-5.15, we
can drop this change.

Fixes: c57796aabfa0 ("Make a franken' build for kleaf until we rebase to android-mainline")
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I3a77119d1a8f66c0979cd1e402dccd5784039eb5